name: OnePlus Firmware Modification

on:
  workflow_dispatch:
    inputs:
      firmware_url:
        description: 'URL of the OnePlus firmware (e.g., direct download link to .zip)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip e2fsprogs rsync

    - name: Clone payload_dumper
      run: |
        git clone https://github.com/vm03/payload_dumper.git
        pip install -r payload_dumper/requirements.txt || echo "No requirements.txt or dependencies already met."

    - name: Make script executable
      run: chmod +x firmware_mod.sh

    - name: Run Firmware Modification Script
      run: |
        ./firmware_mod.sh
      env:
        FIRMWARE_URL: ${{ github.event.inputs.firmware_url }}

    - name: Upload Modified Firmware (system_new.img)
      uses: actions/upload-artifact@v4
      with:
        name: modified-firmware
        path: output/system_new.img
        retention-days: 7
